# Generated by Django 3.0.5 on 2020-04-29 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fitting_orders',
            fields=[
                ('fit_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('fit_date', models.DateTimeField()),
                ('email', models.EmailField(max_length=254)),
                ('comment', models.TextField(max_length=500)),
            ],
        ),
    ]
