# Generated by Django 3.0.5 on 2020-04-30 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fitting_orders',
            new_name='Fitting_order',
        ),
    ]
